# 서버 실행시 자동으로 로딩, ex) DB 설정, 로깅 설정 정보 등

spring:

  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true

  sql:
    init:
      mode: never  # data.sql 자동 실행 방지

  # Docker PostgreSQL 접속 정보
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/archive}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:1234}




rss:
  collect-fixed-rate: 100000
  feeds:
    - url: https://news.google.com/rss?hl=ko&gl=KR&ceid=KR:ko
      source: GOOGLE
    - url: https://news.hada.io/rss/news
      source: HADA
