CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,

                       CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE news (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title VARCHAR(255) NOT NULL,
                      url VARCHAR(2048) NOT NULL,
                      publisher VARCHAR(255),
                      published_at TIMESTAMP(6),
                      fetched_at TIMESTAMP(6),
                      authorship VARCHAR(255),
                      description TEXT,

                      CONSTRAINT uk_news_url UNIQUE (url)
);

CREATE TABLE bookmark (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          user_id BIGINT NOT NULL,
                          news_id BIGINT NOT NULL,
                          created_at TIMESTAMP(6),

                          CONSTRAINT uk_bookmark_user_news
                              UNIQUE (user_id, news_id),

                          CONSTRAINT fk_bookmark_user
                              FOREIGN KEY (user_id)
                                  REFERENCES users (id),

                          CONSTRAINT fk_bookmark_news
                              FOREIGN KEY (news_id)
                                  REFERENCES news (id)
);

CREATE INDEX idx_bookmark_user_id
    ON bookmark (user_id);

CREATE INDEX idx_bookmark_news_id
    ON bookmark (news_id);

CREATE INDEX idx_news_published_at
    ON news (published_at);